# Generated by Django 4.2.16 on 2024-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lawyer', 'Lawyer'), ('admin', 'Admin'), ('client', 'Client')], default='user', max_length=10),
        ),
    ]
