# Generated by Django 4.2.16 on 2024-11-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
