# Generated by Django 4.2.16 on 2024-10-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='related_case',
        ),
        migrations.AddField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billing',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_billings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
