# Generated by Django 4.2.16 on 2024-10-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billing_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
